#version: '3.9'
#
#services:
#
#  db:
#    image: postgres:14.2-alpine
#    restart: unless-stopped
#    ports:
#      - '5432:5432'
#    environment:
#      POSTGRES_DB: railway
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: XbEZZ7ze9Sl78z96TU54
#    volumes:
#      - postgresql-data:/var/lib/postgresql/data
#
#  app:
#    build: .
#    restart: unless-stopped
#    ports:
#      - '8000:8000'
#    depends_on:
#      - db
#    environment:
#      NextRoofWeb_CORE_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
#      NextRoofWeb_CORE_SETTING_LOCAL_SETTINGS_PATH: 'local/settings.prod.py'
#
#volumes:
#  postgresql-data:
#    driver: local
