version: '3.9'

services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      # Uncomment the following line once you set up SSL
      #- "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Uncomment the following line once you set up SSL
      #- ./path/to/certificates:/etc/nginx/certs:ro
    depends_on:
      - app
  reverse-proxy:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      # Uncomment below lines for production with real domain
      #- "--certificatesresolvers.myresolver.acme.email=yoavlv12@email.com"
      #- "--certificatesresolvers.myresolver.acme.storage=acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      # Uncomment below line for production with real domain
#      #- ./acme.json:/acme.json
  db:
    image: postgres:15.1-alpine
    restart: unless-stopped
#    ports:
#      - '5432:5432'
    environment:
      POSTGRES_DB: nextroof_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 43234323
    volumes:
      - postgresql-data:/var/lib/postgresql/data
#      - ./local/local_db.sql:/docker-entrypoint-initdb.d/local_db.sql

  app:
    build: .
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mywebapp.rule=Host(`nextroof.co.il`)"
      - "traefik.http.routers.mywebapp.entrypoints=web"
      # Uncomment below lines for production with real domain
      #- "traefik.http.routers.mywebapp.tls=true"
      #- "traefik.http.routers.mywebapp.tls.certresolver=myresolver"
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      NextRoofWeb_CORE_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
      NextRoofWeb_CORE_SETTING_LOCAL_SETTINGS_PATH: 'core/NextRoofWeb/settings/base.py'

volumes:
  postgresql-data:
    driver: local
