# Generated by Django 4.2.4 on 2023-10-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(name='UserProfile', ),
        migrations.DeleteModel(name='Deals', ),
    ]
